import ReactDataGrid from '@inovua/reactdatagrid-community';
import NumberFilter from '@inovua/reactdatagrid-community/NumberFilter';
import SelectFilter from '@inovua/reactdatagrid-community/SelectFilter';
import '@inovua/reactdatagrid-community/index.css'
import dataSource from '../dataSource.json'

export default function DataGridTable() {

  const gridStyle = { minHeight: 550 };

  const filterValue = [
    { name: 'country', operator: 'inlist', type: 'select' },
    { name: 'total', operator: 'gte', type: 'number', value: 0 },
    { name: 'agricultureNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'agricultureNC', operator: 'gte', type: 'number', value: 0 },
    { name: 'manufacturingAndEnergyProductionNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'manufacturingAndEnergyProductionNC', operator: 'gte', type: 'number', value: 0 },
    { name: 'constructionNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'constructionNC', operator: 'gte', type: 'number', value: 0 },
    { name: 'transportNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'transportNC', operator: 'gte', type: 'number', value: 0 },
    { name: 'wasteManagementNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'wasteManagementNC', operator: 'gte', type: 'number', value: 0 },
    { name: 'otherTertiaryAndHouseholdsNCPlus', operator: 'gte', type: 'number', value: 0 },
    { name: 'otherTertiaryAndHouseholdsNC', operator: 'gte', type: 'number', value: 0 }
  ];

  const columns = [
    { name: 'country', header: 'Country', filterEditor: SelectFilter },
    { name: 'total', header: 'Total', type: 'number', filterEditor: NumberFilter },
    { name: 'agricultureNCPlus', header: 'Agriculture NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'agricultureNC', header: 'Agriculture NC', type: 'number', filterEditor: NumberFilter },
    { name: 'manufacturingAndEnergyProductionNCPlus', header: 'Manufacturing And Energy Production NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'manufacturingAndEnergyProductionNC', header: 'Manufacturing And Energy Production NC', type: 'number', filterEditor: NumberFilter },
    { name: 'constructionNCPlus', header: 'Construction NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'constructionNC', header: 'Construction NC', type: 'number', filterEditor: NumberFilter },
    { name: 'transportNCPlus', header: 'Transport NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'transportNC', header: 'Transport NC', type: 'number', filterEditor: NumberFilter },
    { name: 'wasteManagementNCPlus', header: 'Waste Management NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'wasteManagementNC', header: 'Waste Management NC', type: 'number', filterEditor: NumberFilter },
    { name: 'otherTertiaryAndHouseholdsNCPlus', header: 'Other Tertiary And Households NC+', type: 'number', filterEditor: NumberFilter },
    { name: 'otherTertiaryAndHouseholdsNC', header: 'Other Tertiary And Households NC', type: 'number', filterEditor: NumberFilter },
    { name: 'ecosystemTypes', header: 'Ecosystem Types' }
  ];

  const rows = [
    {
      country: 'AT',
      total: 955.47,
      agricultureNCPlus: 18.65,
      agricultureNC: 2.78,
      manufacturingAndEnergyProductionNCPlus: 67.74,
      manufacturingAndEnergyProductionNC: 11.07,
      constructionNCPlus: 4.4,
      constructionNC: 0.58,
      transportNCPlus: 72.96,
      transportNC: 11.65,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 661.33,
      otherTertiaryAndHouseholdsNC: 104.3,
      ecosystemTypes: null,
    },
    {
      country: 'BE',
      total: 708.76,
      agricultureNCPlus: 10.95,
      agricultureNC: 1.57,
      manufacturingAndEnergyProductionNCPlus: 91.51,
      manufacturingAndEnergyProductionNC: 11.99,
      constructionNCPlus: 2.46,
      constructionNC: 0.39,
      transportNCPlus: 25.55,
      transportNC: 3.7,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 490.61,
      otherTertiaryAndHouseholdsNC: 70.03,
      ecosystemTypes: null,
    },
    {
      country: 'BG',
      total: 65.82,
      agricultureNCPlus: 2.55,
      agricultureNC: 1.54,
      manufacturingAndEnergyProductionNCPlus: 10.63,
      manufacturingAndEnergyProductionNC: 4.61,
      constructionNCPlus: 0.02,
      constructionNC: 0.01,
      transportNCPlus: 4.24,
      transportNC: 2.7,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 26.84,
      otherTertiaryAndHouseholdsNC: 12.69,
      ecosystemTypes: null,
    },
    {
      country: 'CZ',
      total: 429.07,
      agricultureNCPlus: 8.26,
      agricultureNC: 1.26,
      manufacturingAndEnergyProductionNCPlus: 81.68,
      manufacturingAndEnergyProductionNC: 11.81,
      constructionNCPlus: 0.45,
      constructionNC: 0.1,
      transportNCPlus: 20.85,
      transportNC: 3.29,
      wasteManagementNCPlus: 0.01,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 257.66,
      otherTertiaryAndHouseholdsNC: 43.71,
      ecosystemTypes: null,
    },
    {
      country: 'DE',
      total: 3728.39,
      agricultureNCPlus: 147.12,
      agricultureNC: 30.28,
      manufacturingAndEnergyProductionNCPlus: 593.39,
      manufacturingAndEnergyProductionNC: 120.76,
      constructionNCPlus: 12.25,
      constructionNC: 2.77,
      transportNCPlus: 207.03,
      transportNC: 47.08,
      wasteManagementNCPlus: 0.01,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 2106.25,
      otherTertiaryAndHouseholdsNC: 461.46,
      ecosystemTypes: null,
    },
    {
      country: 'DK',
      total: 22.07,
      agricultureNCPlus: 1.04,
      agricultureNC: 0.36,
      manufacturingAndEnergyProductionNCPlus: 0.42,
      manufacturingAndEnergyProductionNC: 0.09,
      constructionNCPlus: null,
      constructionNC: 0.01,
      transportNCPlus: 0.58,
      transportNC: 0.21,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 14.44,
      otherTertiaryAndHouseholdsNC: 4.91,
      ecosystemTypes: null,
    },
    {
      country: 'EE',
      total: 40.16,
      agricultureNCPlus: 2.18,
      agricultureNC: 1.52,
      manufacturingAndEnergyProductionNCPlus: 1.02,
      manufacturingAndEnergyProductionNC: 1.32,
      constructionNCPlus: 0.23,
      constructionNC: 0.34,
      transportNCPlus: 3.26,
      transportNC: 1.91,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 16.25,
      otherTertiaryAndHouseholdsNC: 12.12,
      ecosystemTypes: null,
    },
    {
      country: 'EL',
      total: 38.57,
      agricultureNCPlus: 2.83,
      agricultureNC: 3.51,
      manufacturingAndEnergyProductionNCPlus: 1.26,
      manufacturingAndEnergyProductionNC: 5.69,
      constructionNCPlus: 0.17,
      constructionNC: 2.12,
      transportNCPlus: 2.96,
      transportNC: 5,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 11.26,
      otherTertiaryAndHouseholdsNC: 3.77,
      ecosystemTypes: null,
    },
    {
      country: 'ES',
      total: 508.83,
      agricultureNCPlus: 11.46,
      agricultureNC: 13.94,
      manufacturingAndEnergyProductionNCPlus: 82.15,
      manufacturingAndEnergyProductionNC: 37.94,
      constructionNCPlus: 9.09,
      constructionNC: 4.84,
      transportNCPlus: 37.98,
      transportNC: 40.22,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 168.88,
      otherTertiaryAndHouseholdsNC: 102.33,
      ecosystemTypes: null,
    },
    {
      country: 'FI',
      total: 809.2,
      agricultureNCPlus: 10.39,
      agricultureNC: 4.85,
      manufacturingAndEnergyProductionNCPlus: 30.02,
      manufacturingAndEnergyProductionNC: 15.28,
      constructionNCPlus: 0.04,
      constructionNC: 1.11,
      transportNCPlus: 45.34,
      transportNC: 31.35,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 495.24,
      otherTertiaryAndHouseholdsNC: 175.58,
      ecosystemTypes: null,
    },
    {
      country: 'FR',
      total: 2441.7,
      agricultureNCPlus: 125.8,
      agricultureNC: 25.39,
      manufacturingAndEnergyProductionNCPlus: 268.46,
      manufacturingAndEnergyProductionNC: 46.93,
      constructionNCPlus: 3.77,
      constructionNC: 0.68,
      transportNCPlus: 223.9,
      transportNC: 55.7,
      wasteManagementNCPlus: 0.01,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 1428.6,
      otherTertiaryAndHouseholdsNC: 262.47,
      ecosystemTypes: null,
    },
    {
      country: 'HR',
      total: 55.03,
      agricultureNCPlus: 0.59,
      agricultureNC: 15.14,
      manufacturingAndEnergyProductionNCPlus: null,
      manufacturingAndEnergyProductionNC: 6.35,
      constructionNCPlus: null,
      constructionNC: 0.23,
      transportNCPlus: 0.31,
      transportNC: 11.57,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 0.28,
      otherTertiaryAndHouseholdsNC: 20.54,
      ecosystemTypes: null,
    },
    {
      country: 'HU',
      total: 161.37,
      agricultureNCPlus: 26.89,
      agricultureNC: 5.14,
      manufacturingAndEnergyProductionNCPlus: 13.34,
      manufacturingAndEnergyProductionNC: 2.47,
      constructionNCPlus: 1.55,
      constructionNC: 0.31,
      transportNCPlus: 15.25,
      transportNC: 3.06,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 78.76,
      otherTertiaryAndHouseholdsNC: 14.59,
      ecosystemTypes: null,
    },
    {
      country: 'IE',
      total: 155.73,
      agricultureNCPlus: 15.28,
      agricultureNC: 5.93,
      manufacturingAndEnergyProductionNCPlus: 6.36,
      manufacturingAndEnergyProductionNC: 1.33,
      constructionNCPlus: 0.15,
      constructionNC: 0.04,
      transportNCPlus: 11.53,
      transportNC: 4.6,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 80.43,
      otherTertiaryAndHouseholdsNC: 30.08,
      ecosystemTypes: null,
    },
    {
      country: 'IT',
      total: 504.17,
      agricultureNCPlus: 20.04,
      agricultureNC: 4.69,
      manufacturingAndEnergyProductionNCPlus: 88.22,
      manufacturingAndEnergyProductionNC: 15.64,
      constructionNCPlus: 3.06,
      constructionNC: 0.87,
      transportNCPlus: 52.16,
      transportNC: 10.48,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 264.32,
      otherTertiaryAndHouseholdsNC: 44.68,
      ecosystemTypes: null,
    },
    {
      country: 'LT',
      total: 190.35,
      agricultureNCPlus: 6.65,
      agricultureNC: 3.99,
      manufacturingAndEnergyProductionNCPlus: 11.54,
      manufacturingAndEnergyProductionNC: 6.41,
      constructionNCPlus: 0.7,
      constructionNC: 0.33,
      transportNCPlus: 6.98,
      transportNC: 3.87,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 82.83,
      otherTertiaryAndHouseholdsNC: 67.04,
      ecosystemTypes: null,
    },
    {
      country: 'LU',
      total: 164.68,
      agricultureNCPlus: 1.27,
      agricultureNC: 0.16,
      manufacturingAndEnergyProductionNCPlus: 9.79,
      manufacturingAndEnergyProductionNC: 1.27,
      constructionNCPlus: 1.38,
      constructionNC: 0.17,
      transportNCPlus: 15.46,
      transportNC: 2,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 117.82,
      otherTertiaryAndHouseholdsNC: 15.36,
      ecosystemTypes: null,
    },
    {
      country: 'LV',
      total: 343.4,
      agricultureNCPlus: 7.07,
      agricultureNC: 6.38,
      manufacturingAndEnergyProductionNCPlus: 24.32,
      manufacturingAndEnergyProductionNC: 15.38,
      constructionNCPlus: 2.8,
      constructionNC: 0.75,
      transportNCPlus: 11.74,
      transportNC: 8.19,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 167.53,
      otherTertiaryAndHouseholdsNC: 99.23,
      ecosystemTypes: null,
    },
    {
      country: 'NL',
      total: 1045.98,
      agricultureNCPlus: 70.23,
      agricultureNC: 2.66,
      manufacturingAndEnergyProductionNCPlus: 138.57,
      manufacturingAndEnergyProductionNC: 4.74,
      constructionNCPlus: 81.89,
      constructionNC: 3.11,
      transportNCPlus: 103.03,
      transportNC: 4,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 613.45,
      otherTertiaryAndHouseholdsNC: 24.31,
      ecosystemTypes: null,
    },
    {
      country: 'PL',
      total: 1455.49,
      agricultureNCPlus: 66.21,
      agricultureNC: 27.05,
      manufacturingAndEnergyProductionNCPlus: 78.51,
      manufacturingAndEnergyProductionNC: 22.51,
      constructionNCPlus: 7.74,
      constructionNC: 2.05,
      transportNCPlus: 45.25,
      transportNC: 18.79,
      wasteManagementNCPlus: 0.01,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 865.97,
      otherTertiaryAndHouseholdsNC: 321.39,
      ecosystemTypes: null,
    },
    {
      country: 'PT',
      total: 68.49,
      agricultureNCPlus: 1.17,
      agricultureNC: 4.34,
      manufacturingAndEnergyProductionNCPlus: 1.87,
      manufacturingAndEnergyProductionNC: 4.51,
      constructionNCPlus: 0.41,
      constructionNC: 5.51,
      transportNCPlus: 3.33,
      transportNC: 11.69,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 11.38,
      otherTertiaryAndHouseholdsNC: 24.27,
      ecosystemTypes: null,
    },
    {
      country: 'RO',
      total: 199.09,
      agricultureNCPlus: 12.03,
      agricultureNC: 5.19,
      manufacturingAndEnergyProductionNCPlus: 11.2,
      manufacturingAndEnergyProductionNC: 5.68,
      constructionNCPlus: 0.17,
      constructionNC: 0.12,
      transportNCPlus: 7.49,
      transportNC: 3.67,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 107.44,
      otherTertiaryAndHouseholdsNC: 46.1,
      ecosystemTypes: null,
    },
    {
      country: 'SE',
      total: 1300.84,
      agricultureNCPlus: 13.45,
      agricultureNC: 8.05,
      manufacturingAndEnergyProductionNCPlus: 90.26,
      manufacturingAndEnergyProductionNC: 39.74,
      constructionNCPlus: 0.75,
      constructionNC: 0.87,
      transportNCPlus: 46.24,
      transportNC: 66.91,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 582.51,
      otherTertiaryAndHouseholdsNC: 452.06,
      ecosystemTypes: null,
    },
    {
      country: 'SI',
      total: 106.28,
      agricultureNCPlus: 3,
      agricultureNC: 0.95,
      manufacturingAndEnergyProductionNCPlus: 15.95,
      manufacturingAndEnergyProductionNC: 5.18,
      constructionNCPlus: 0.14,
      constructionNC: 0.04,
      transportNCPlus: 14.05,
      transportNC: 5.32,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 51.03,
      otherTertiaryAndHouseholdsNC: 10.65,
      ecosystemTypes: null,
    },
    {
      country: 'SK',
      total: 128.12,
      agricultureNCPlus: 5.19,
      agricultureNC: 0.73,
      manufacturingAndEnergyProductionNCPlus: 17.92,
      manufacturingAndEnergyProductionNC: 2.67,
      constructionNCPlus: 1.18,
      constructionNC: 0.17,
      transportNCPlus: 8.33,
      transportNC: 1.39,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 78.18,
      otherTertiaryAndHouseholdsNC: 12.36,
      ecosystemTypes: null,
    },
    {
      country: 'UK',
      total: 684.66,
      agricultureNCPlus: 27.05,
      agricultureNC: 4.75,
      manufacturingAndEnergyProductionNCPlus: 86.18,
      manufacturingAndEnergyProductionNC: 13.12,
      constructionNCPlus: 2.09,
      constructionNC: 0.4,
      transportNCPlus: 33.87,
      transportNC: 6.15,
      wasteManagementNCPlus: null,
      wasteManagementNC: null,
      otherTertiaryAndHouseholdsNCPlus: 440.88,
      otherTertiaryAndHouseholdsNC: 70.18,
      ecosystemTypes: null,
    },
    {
      country: 'EU',
      total: 16311.72,
      agricultureNCPlus: 617.36,
      agricultureNC: 182.14,
      manufacturingAndEnergyProductionNCPlus: 1822.33,
      manufacturingAndEnergyProductionNC: 414.5,
      constructionNCPlus: 136.9,
      constructionNC: 27.92,
      transportNCPlus: 1019.67,
      transportNC: 364.49,
      wasteManagementNCPlus: 0.06,
      wasteManagementNC: 0.01,
      otherTertiaryAndHouseholdsNCPlus: 9220.15,
      otherTertiaryAndHouseholdsNC: 2506.2,
      ecosystemTypes: null,
    }
  ];

  return (
    <div className="container text-center my-3">
      <h1 className="mb-5">React Data Grid Table</h1>
      <div className="container">
        <ReactDataGrid
          style={gridStyle}
          columns={columns}
          dataSource={dataSource}
          defaultFilterValue={filterValue}
          enableFiltering={true} />
      </div>
    </div>
  )
}
